name: SSBGeyser
version: '${version}'
main: com.siberanka.ssbgeyser.SSBGeyser
api-version: '1.21'
author: siberanka
description: SuperiorSkyblock2 Bedrock/Floodgate GUI adaptation addon.
depend:
  - SuperiorSkyblock2
  - floodgate
softdepend:
  - Geyser-Spigot
commands:
  ssbgeyser:
    description: Main command of SSBGeyser
    permission: ssbgeyser.admin
    usage: /<command> reload
